In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [3]:
path_to_file='shakespeare.txt'

In [4]:
text=open(path_to_file,'r').read()

In [5]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [6]:
vocab=sorted(set(text))

In [7]:
len(vocab)

84

In [8]:
for pair in enumerate(vocab):
    print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [9]:
char_to_ind={char:ind for ind,char in enumerate(vocab)}

In [10]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [11]:
int_to_char=np.array(vocab)

In [12]:
encoded_text=np.array([char_to_ind[c] for c in text])

In [13]:
encoded_text

array([ 0,  1,  1, ..., 30, 39, 29])

In [14]:
sample=text[:500]
sample

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [15]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [16]:
print(text[:500])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bu


In [17]:
line='From fairest creatures we desire increase'

In [18]:
len(line)

41

In [19]:
lines='''
 From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease
'''

In [20]:
len(lines)

133

In [21]:
seq_len=120

In [22]:
total_num_seq=len(text)//(seq_len+1)

In [23]:
total_num_seq

45005

In [24]:
char_dataset=tf.data.Dataset.from_tensor_slices(encoded_text)

In [25]:
type(char_dataset)

tensorflow.python.data.ops.dataset_ops.TensorSliceDataset

In [26]:
sequence=char_dataset.batch(seq_len+1,drop_remainder=True)

In [27]:
def create_sequence(seq):
    input_text=seq[:-1]
    target_text=seq[1:]
    return input_text,target_text

In [28]:
dataset=sequence.map(create_sequence)

In [29]:
dataset

<MapDataset shapes: ((120,), (120,)), types: (tf.int64, tf.int64)>

In [30]:
for input_txt,target_txt in dataset.take(1):
    print(input_txt.numpy())
    print(''.join(int_to_char[input_txt.numpy()]))
    print('\n')
    print(target_txt.numpy())
    print(''.join(int_to_char[target_txt.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But


[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [31]:
batch_size=128

In [32]:
buffer_size=10000
dataset=dataset.shuffle(buffer_size).batch(batch_size,drop_remainder=True)

In [33]:
dataset

<BatchDataset shapes: ((128, 120), (128, 120)), types: (tf.int64, tf.int64)>

In [34]:
vocab_size=len(vocab)

In [35]:
vocab_size

84

In [36]:
embed_dim=64

In [37]:
rnn_nuerons=1050

In [38]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [39]:
def sparse_cat_loss(y_true,y_pred):
    return sparse_categorical_crossentropy(y_true,y_pred,from_logits=True)

In [40]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,GRU,Dense

In [41]:
def create_model(vocab_size,embed_dim,rnn_nuerons,batch_size):
    model=Sequential()
    model.add(Embedding(vocab_size,embed_dim,batch_input_shape=[batch_size,None]))
    model.add(GRU(rnn_nuerons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
    model.add(Dense(vocab_size))
    model.compile('adam',loss=sparse_cat_loss)
    return model

In [42]:
model=create_model(vocab_size=vocab_size,embed_dim=embed_dim,rnn_nuerons=rnn_nuerons,batch_size=batch_size)

In [43]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (128, None, 64)           5376      
_________________________________________________________________
gru (GRU)                    (128, None, 1050)         3515400   
_________________________________________________________________
dense (Dense)                (128, None, 84)           88284     
Total params: 3,609,060
Trainable params: 3,609,060
Non-trainable params: 0
_________________________________________________________________


In [44]:
for input_example_batch,target_examp in dataset.take(1):
    example_batch_prediction=model(input_example_batch)

In [45]:
sample_indecis=tf.random.categorical(example_batch_prediction[0],num_samples=1)

In [46]:
sample_indecis=tf.squeeze(sample_indecis,axis=-1).numpy()

In [47]:
sample_indecis

array([75, 36, 31, 26, 63,  5, 80, 77, 23, 31, 28, 70, 47,  6, 31, 61, 82,
       52, 57, 70, 57, 36, 66, 40, 58, 43, 53, 25, 33, 15, 14,  6, 19, 62,
       82, 28, 68,  0, 45, 28, 30, 25, 24, 50,  1, 57, 64, 33, 14, 74, 47,
       75, 59, 21, 20, 12,  8, 39, 51, 40, 79, 55, 54, 11, 35, 83, 24, 77,
       18, 11,  0,  2, 71, 18,  6, 79, 35, 30, 67, 58,  4, 82, 42, 32, 16,
        4, 46, 64, 22, 53, 66, 58, 25, 36, 20, 50, 51, 18, 53, 16, 80, 18,
       74, 50, 11, 38, 44,  7, 57, 79, 75, 39, 24,  7,  1, 24, 27, 78,  7,
       79])

In [48]:
int_to_char[sample_indecis]

array(['t', 'K', 'F', 'A', 'h', "'", 'y', 'v', '<', 'F', 'C', 'o', 'V',
       '(', 'F', 'f', '|', '[', 'b', 'o', 'b', 'K', 'k', 'O', 'c', 'R',
       ']', '?', 'H', '4', '3', '(', '8', 'g', '|', 'C', 'm', '\n', 'T',
       'C', 'E', '?', '>', 'Y', ' ', 'b', 'i', 'H', '3', 's', 'V', 't',
       'd', ':', '9', '1', ',', 'N', 'Z', 'O', 'x', '`', '_', '0', 'J',
       '}', '>', 'v', '7', '0', '\n', '!', 'p', '7', '(', 'x', 'J', 'E',
       'l', 'c', '&', '|', 'Q', 'G', '5', '&', 'U', 'i', ';', ']', 'k',
       'c', '?', 'K', '9', 'Y', 'Z', '7', ']', '5', 'y', '7', 's', 'Y',
       '0', 'M', 'S', ')', 'b', 'x', 't', 'N', '>', ')', ' ', '>', 'B',
       'w', ')', 'x'], dtype='<U1')

In [49]:
epochs=50

In [50]:
model.fit(dataset ,epochs=epochs)

Epoch 1/50
351/351 [==============================] - 49s 132ms/step - loss: 3.1183
Epoch 2/50
351/351 [==============================] - 51s 141ms/step - loss: 1.8324
Epoch 3/50
351/351 [==============================] - 51s 142ms/step - loss: 1.5077
Epoch 4/50
351/351 [==============================] - 51s 142ms/step - loss: 1.3652
Epoch 5/50
351/351 [==============================] - 50s 140ms/step - loss: 1.2912
Epoch 6/50
351/351 [==============================] - 51s 142ms/step - loss: 1.2479
Epoch 7/50
351/351 [==============================] - 50s 140ms/step - loss: 1.2168
Epoch 8/50
351/351 [==============================] - 50s 140ms/step - loss: 1.1920
Epoch 9/50
351/351 [==============================] - 50s 140ms/step - loss: 1.1710
Epoch 10/50
351/351 [==============================] - 51s 142ms/step - loss: 1.1524
Epoch 11/50
351/351 [==============================] - 51s 142ms/step - loss: 1.1352
Epoch 12/50
351/351 [==============================] - 50s 140ms/step - lo

In [51]:
model.save('text_genrator.h5')

In [52]:
from tensorflow.keras.models import load_model

In [53]:
model=create_model(vocab_size,embed_dim,rnn_nuerons,batch_size=1)
model.load_weights('text_genrator.h5')
model.build(tf.TensorShape([1,None]))



In [54]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (1, None, 64)             5376      
_________________________________________________________________
gru_1 (GRU)                  (1, None, 1050)           3515400   
_________________________________________________________________
dense_1 (Dense)              (1, None, 84)             88284     
Total params: 3,609,060
Trainable params: 3,609,060
Non-trainable params: 0
_________________________________________________________________


In [55]:
def genrate_text(model,start_seed,gen_size=100,temp=0.1):
  num_genrate=gen_size
  input_eval=[char_to_ind[s] for s in start_seed]
  input_eval=tf.expand_dims(input_eval,0)
  text_genrated=[]
  temperature=temp
  model.reset_states()
  for i in range(num_genrate):
    predictions=model(input_eval)
    predictions=tf.squeeze(predictions,0)
    predictions=predictions/temperature
    predicted_id=tf.random.categorical(predictions,num_samples=1)[-1,0].numpy()
    input_eval=tf.expand_dims([predicted_id],0)
    text_genrated.append(int_to_char[predicted_id])
  return(start_seed +''.join(text_genrated))  

In [68]:
print(genrate_text(model,'DUKE',gen_size=10000))

DUKE. It is the cause of his advantage of his life,
    I would not have it so. The strong instruction
    That shall be prov'd by the forest looks of thee.
    But if thou liest, thou shalt not have the heart.
    I will not speak to thee.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        